services:
  cube_api:
    build: .
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "--factory",
        "app:create_app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
    container_name: cube-api
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:8000
    depends_on:
      - mongo
    volumes:
      - ~/cube-api-config/instance/:/cube-api/instance/

  mongo:
    restart: always
    image: mongo:latest
    container_name: cube-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - cube-mongodata:/data/db

volumes:
  cube-mongodata:
